# Generated by Django 2.2.10 on 2020-03-05 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20200225_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationRequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('IM', 'Implementado'), ('PN', 'Pendiente')], default='PN', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_requests', to='project.Project')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationRequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=80)),
                ('tasks', models.CharField(max_length=200)),
                ('observations', models.CharField(max_length=500)),
                ('request_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_details', to='request.ImplementationRequestHeader')),
            ],
            options={
                'ordering': ['-package'],
            },
        ),
    ]
