# Generated by Django 2.2.11 on 2020-04-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20200415_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementationrequestheader',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='implementationrequestheader',
            name='request_date',
        ),
    ]
