# Generated by Django 2.1.15 on 2020-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20200415_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationrequestheader',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
    ]
