# Generated by Django 2.1.15 on 2021-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20200520_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationrequestdetail',
            name='package',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='implementationrequestdetail',
            name='tasks',
            field=models.CharField(max_length=1000),
        ),
    ]
