# Generated by Django 2.2.10 on 2020-02-24 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('actived', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Motivo')),
                ('disabled_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Baja')),
                ('package_name', models.CharField(max_length=100, verbose_name='Nombre Paquete')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'ordering': ['-package_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('actived', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Motivo')),
                ('disabled_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Baja')),
                ('project_name', models.CharField(max_length=100, verbose_name='Nombre Proyecto')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-project_name'],
            },
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('actived', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Motivo')),
                ('disabled_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Baja')),
                ('task_name', models.CharField(max_length=100, verbose_name='Nombre Tarea')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.Package')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-task_name'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='project.Project'),
        ),
    ]
