# Generated by Django 2.2.10 on 2020-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='disabled_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disabled_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='task',
            name='disabled_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha Baja'),
        ),
    ]
