# Generated by Django 2.2.11 on 2020-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200225_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='disabled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='package',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disabled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='disabled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo'),
        ),
    ]
