# Generated by Django 2.1.15 on 2020-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200305_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['package_name'], 'verbose_name': 'paquete', 'verbose_name_plural': 'paquetes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_name'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_name'], 'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterField(
            model_name='package',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
    ]
