# Generated by Django 2.1.15 on 2021-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200520_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=1000, verbose_name='Nombre Tarea'),
        ),
    ]
