# Generated by Django 2.2.11 on 2020-04-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0004_auto_20200415_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Deploy')),
                ('lsn', models.PositiveIntegerField()),
                ('deploy_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_info', to='request.ImplementationRequestHeader')),
            ],
            options={
                'verbose_name': 'deploy Detalle',
                'verbose_name_plural': 'deploys Detalles',
                'ordering': ['-deploy_date'],
            },
        ),
    ]
